データ型判定メソッドの作成
ok-os-job-change-team/kaito-backend-bootcamp pull request #12
Opened 2023-07-21 15:53 UTC by Kaito1290

## 概要
あるデータを受け取り、StringかNumericかArrayかHashかを判定するメソッドの作成

## 対応するissues
- https://github.com/ok-os-job-change-team/kaito-backend-bootcamp/issues/11

2023-07-21 15:55 UTC, Kaito1290 commented
こんな脳筋のやりかたでいいのか？？？

**出力結果**
```
Ono Kaito@LAPTOP-V6212LQV MINGW64 ~/work/kaito-backend-bootcamp (conditional_bra
nch_application)
$ ruby data_type_judgement.rb
String です。

Numeric です。

Array です。

Hash です。
```

2023-07-22 07:13 UTC, ochi-sho-private-study requested changes
@Kaito1290 
コメントしたよ！

2023-07-22 07:13 UTC, kakeru-one commented on data_type_judgement.rb
> +puts(data_type_judgement(123))
FYI

実は厳密に言うと、`123`のような整数は、
NumericクラスのサブクラスであるIntegerクラスのインスタンスだったりします。
`1.5`などの少数だと、Floatクラスのインスタンスです。
(とはいえ、今回はそこまで厳密に判定しなくていいので、このままで良いです。)

NumericクラスのRef: https://docs.ruby-lang.org/ja/latest/class/Numeric.html
IntegerクラスのRef: https://docs.ruby-lang.org/ja/latest/class/Integer.html

2023-07-22 07:13 UTC, ochi-sho-private-study commented on data_type_judgement.rb
> +end
ちなみに、どのクラスなのか？を返すだけであれば、
以下のようなコードにできます。

```ruby
def data_type_judgement(data)
  "#{data.class}です。"
end
```

2023-07-22 07:13 UTC, ochi-sho-private-study commented on data_type_judgement.rb
> +end
現状のコードだと、
String/Numeric/Array/Hashクラス以外または、そのサブクラス以外のインスタンスの場合、
Hashクラスのインスタンスだと判定されるので、条件分岐を一個増やそう。
その時の標準出力は`'判定できないデータです。'`と出力するようにしよう。

```
class User
end

user = User.new
puts(data_type_judgement(user))

# => Hash です。
```

## 出力結果
![スクリーンショット 2023-07-22 16 11 52](https://github.com/ok-os-job-change-team/kaito-backend-bootcamp/assets/118090073/b4047a44-4b59-4420-b13f-28edb53702cf)

2023-07-22 13:54 UTC, Kaito1290 commented on data_type_judgement.rb
> +puts(data_type_judgement(123))
**整数クラス(Integer)** は、大きいくくりで**数値クラス(Numeric)** に属している
っていう理解であってる？

2023-07-22 14:07 UTC, Kaito1290 commented on data_type_judgement.rb
> +end
修正しました → https://github.com/ok-os-job-change-team/kaito-backend-bootcamp/pull/12/commits/b1b2414566bb573de06250d61031db264747235d

p.s
if文の仕様が頭から抜けてたわ
まだこのくらいなら簡単やけど、未定義動作って考えるの難しいよな...

2023-07-22 14:40 UTC, ochi-sho-private-study approved these changes
色々コメントしたけど、LGTM!
(コメントは読んでね。わからなかったら質問してもらっていいので！)

![LGTM](https://media.giphy.com/media/xT9DPrC1YWXBO1coyQ/giphy.gif)

2023-07-22 14:40 UTC, ochi-sho-private-study commented on data_type_judgement.rb
> +puts(data_type_judgement(123))
@Kaito1290 
大体そんな感じ！
もっと厳密に言うと、Integerクラスは、Numericクラスを継承してる！
(詳しくはクラスの継承に関して調べてみてね。)

クラスの継承に関するRef: https://www.ruby.or.jp/ja/tech/development/ruby/tutorial/090_class_extension.html

Integerクラスは、Numericクラスを継承しているので、
「IntegerクラスはNumericクラスのサブクラスである」と言うこともある！

2023-07-22 14:40 UTC, ochi-sho-private-study commented on data_type_judgement.rb
> +end
> if文の仕様が頭から抜けてたわ

これはまだrubyの文法に関して、全体像が掴めてないので仕方ないと言えるね。
(より具体的に言うと、今回ではRubyのオブジェクトの概念がわかっていないと予想できない、と言うこと。)

> まだこのくらいなら簡単やけど、未定義動作って考えるの難しいよな...

上記の全体像を掴んだ後でも、エラーハンドリングの漏れはよくあることなので、
実際の使用シーンを全て洗い出せるようになるといいね。

2023-07-23 01:10 UTC, merged